version: "3.8"

services:
  wbs-hub:
    image: wbs-hub:latest
    networks:
      - network_public
    volumes:
      - wbs-data:/app/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.wbs-hub.rule=Host(`wbs.arvsystems.cloud`)
        - traefik.http.routers.wbs-hub.entrypoints=websecure
        - traefik.http.routers.wbs-hub.tls.certresolver=letsencryptresolver
        - traefik.http.services.wbs-hub.loadbalancer.server.port=8501
        - traefik.http.routers.wbs-hub.service=wbs-hub

networks:
  network_public:
    external: true

volumes:
  wbs-data:
